language: java
script:
  #lance les tests
  - mvn clean verify --file ./simple-api/pom.xml

  #docker connexion
  - docker login -u $Dockeruser -p $Dockerpwd

  #docker build
  - docker-compose up

  #docker image
  - docker tag picture_1 $Dockeruser/pictures
  - docker push $Dockeruser/pictures

cache:
directories:
  - $HOME/.m2
services:
  - docker

