language: java
script:
  #lance les tests
  - mvn clean verify --file ./simple-api/pom.xml

  #docker connexion
  - docker login -u $Dockeruser -p $Dockerpwd

  #docker build
  - docker build -t $Dockeruser/pictures:database database
  - docker build -t $Dockeruser/pictures:httpd httpd
  - docker build -t $Dockeruser/pictures:simple-api simple-api

  #docker image
  # - docker tag picture_1 $Dockeruser/pictures
  - docker push $Dockeruser/pictures:database
  - docker push $Dockeruser/pictures:httpd
  - docker push $Dockeruser/pictures:simple-api
