language: java
script:
  #lance les tests
  - mvn clean verify --file ./simple-api/pom.xml
  - mvn clean verify --file ./simple-api/pom.xml org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=Antoine-VILLERS_devops

  #docker connexion
  - docker login -u $Dockeruser -p $Dockerpwd

  #docker build
  - docker build -t $Dockeruser/pictures:database database
  - docker build -t $Dockeruser/pictures:httpd httpd
  - docker build -t $Dockeruser/pictures:simple-api simple-api

  #docker image
  # - docker tag picture_1 $Dockeruser/pictures
  - docker push $Dockeruser/pictures:database
  - docker push $Dockeruser/pictures:httpd
  - docker push $Dockeruser/pictures:simple-api

addons:
  sonarcloud:
    organization: "antoine-villers"
    token:
      secure: "$SONARCLOUD_TOKEN" # encrypted value of your token
